import type { Metadata, Viewport } from "next";
import { Heebo } from "next/font/google";
import ThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import "./globals.css";

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  weight: ["100", "300", "400", "500", "700", "800", "900"],
  display: "swap",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  applicationName: "IsraBis",
  title: {
    default: "IsraBis — השוואת מחירי סופר בין 33 רשתות | מתכונים | AI חכם",
    template: "%s | IsraBis — אפליקציית מחירים ומתכונים",
  },
  description: "אפליקציית השוואת מחירי סופרמרקט חכמה בישראל. השוו מחירים בין 33 רשתות שיווק, גלו מתכונים ללא הגבלה עם מחירים, סרקו מקרר ומוצרים עם AI, נהלו קניות משפחתיות, ועקבו אחרי תקציב המזון — הכל בחינם בעברית.",
  keywords: [
    "השוואת מחירי סופר", "השוואת מחירים סופרמרקט", "השוואת מחירים רשתות שיווק",
    "אפליקציית מתכונים", "אפליקציה למתכונים בעברית", "מתכונים עם מחירים",
    "אפליקציית אוכל חכמה", "אפליקציית מחירים AI", "השוואת מחירי מזון ישראל",
    "חיסכון בקניות סופר", "סריקת מקרר AI", "מתכון מסרטון",
    "רמי לוי מחירים", "שופרסל מחירים", "ויקטורי מחירים",
    "עגלת קניות חכמה", "השוואת סלי קניות", "אפליקציה לחיסכון במזון",
    "מעקב הוצאות מזון", "תקציב קניות משפחתי", "קניות משפחתיות אפליקציה",
    "סריקת ברקוד מחירים", "סריקת קלוריות", "מתכונים ישראליים",
    "IsraBis", "ישראביס",
  ],
  metadataBase: new URL("https://israbis.com"),
  alternates: {
    canonical: "https://israbis.com",
    languages: {
      "he-IL": "https://israbis.com/",
    },
  },
  openGraph: {
    type: "website",
    locale: "he_IL",
    url: "https://israbis.com",
    siteName: "IsraBis",
    title: "IsraBis — השוואת מחירי סופר, מתכונים ללא הגבלה, כלי AI חכמים",
    description: "האפליקציה היחידה בישראל שמשלבת השוואת מחירים בין 33 רשתות שיווק, מתכונים ללא הגבלה עם מחירים, כלי AI חכמים, וניהול קניות משפחתי — בחינם.",
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "IsraBis — השוואת מחירי סופר + מתכונים + AI בישראל",
    description: "השוו מחירים בין 33 רשתות, גלו מתכונים ללא הגבלה, סרקו מקרר וקבלו מתכונים — הכל באפליקציה אחת בעברית.",
    // Twitter image auto-generated by src/app/opengraph-image.tsx
  },
  appLinks: {
    ios: {
      url: "https://apps.apple.com/il/app/israbis/id123456789",
      app_store_id: "123456789",
    },
    android: {
      package: "com.israbis.app",
      app_name: "IsraBis",
    },
    web: {
      url: "https://israbis.com",
      should_fallback: true,
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Add Google Search Console verification after setting it up:
  // verification: { google: "your-real-code-here" },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
    ],
    apple: [
      { url: "/apple-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  manifest: "/manifest.json",
  other: {
    "msapplication-TileColor": "#34C759",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl" className={heebo.className} suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#34C759" />
        {/* Geo meta tags — GEO SEO for Israel */}
        <meta name="geo.region" content="IL" />
        <meta name="geo.country" content="Israel" />
        <meta name="DC.language" content="he" />
        {/* Hreflang for Hebrew Israel */}
        <link rel="alternate" hrefLang="he-IL" href="https://israbis.com/" />
      </head>
      <body>
        <ThemeProvider>
          <JsonLd />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
